### ISSUE TITLE
Allow to update options at anytime

### ISSUE THREAD

**Issue by acfscience** [bleenco/ngx-uploader#101]
Options for NgFileSelectDirective are allowed to be set only when the directive gets initialized. However, there are additional scenarios when I would like to update these before upload such as when I am sending additional data that is entered through a form or when the upload url dynamically changes based on what is been uploaded.

**Comment by wouterhummelink** [comment]
I'm still facing the same problem, even after the pull request that was supposed to fix it I can't seem to get the input to use the updated options after getting the proper metadata.

In the parent component that has options propertybound I try doing this. 
EmailId is propertybound from another parent component.

`    ngOnChanges(changes: {[ propName: string]: SimpleChange}) {

      var newOptions = this.extendedOptions;
      newOptions['url'] = 'http://localhost:8000/api/business/email/'+changes['emailId'].currentValue+'/attachments';      this.extendedOptions = newOptions;
      console.log(this.extendedOptions);
    }
`

**Comment by wouterhummelink** [comment]
Solutions turns out to be to create a copy of the options object, insert the new values and then assign it back to the databound variable:
`
var newOptions = Object.assign({},this.extendedOptions);
`

**Comment by JesusMayuri7** [comment]
this.newOptions = Object.assign({},this.options);
this.newOptions= {data: { some:'foo'}};
 this.options=this.newOptions;

not worked

**Comment by F3L1X79** [comment]
@JesusMayuri7 , the way you should do (from @wouterhummelink  explanations) is:
```
var newOptions = Object.assign({}, this.options);
newOptions['data']['some'] = "foo";
this.options = newOptions;
```

**Comment by KirilVelichkov** [comment]
@F3L1X79  this is still not working. It always send the first assign value when i select an image

**Comment by F3L1X79** [comment]
Well  this is working, in my case. Here is my working code for example (if this might help):
HTML: 
```
<Tree #tree [nodes]="treenodes">
                <template #treeNodeTemplate let-node>
                    <span (click)="treeClick(node)">{{ node.data.name }}</span>
                </template>
            </Tree>
```
ts script: 
```
ngOnInit(): void {
        this.zone = new NgZone({ enableLongStackTrace: false });
        this.options = {
            url: config.uploadFile,
            filterExtensions: true,
            allowedExtensions: ['tif'],
            calculateSpeed: true,
            data: {
                path1: this.selectedPath1,
                path2: this.selectedPath2,
                catId: null
            }
        };
treeClick(node) {
                this.selectedPath1 = 'my custom value'
                var newOptions = Object.assign({}, this.options);
                newOptions['data']['path1'] = this.selectedPath1;
                newOptions['data']['catId'] = node.data.id;
                this.options = newOptions;
    }
}
```

**Comment by saravanakumargn** [comment]
Its not working for me
I tried in beforeUpload event. I want to append selected file name with the url or data

~~~
beforeUpload(uploadingFile): void {
}
~~~

**Comment by rahasal** [comment]
i have same problem with ngx-uploader :-(

**Comment by marekszczepansky** [comment]
It will not work in beforeUpload event - XHR session is already created. To update options you should do this before interact with directive (especially before staring upload). IMO it is useful if you disable autoUpload.

**Comment by erata** [comment]
i have the same problem updating options as options:NgUploaderOptions.
when i change defining  options:any; problem solved. maybe it is not recommenden but solves problem.
