### ISSUE TITLE
How is data property meant to be parsed and why Express example only works partially?

### ISSUE THREAD

**Issue by dragGH102** [bleenco/ngx-uploader#102]
NOTE: I'm using v0.5.6 with Angular 2 rc2

These are the options:

```
            this.options = {
                url: 'http://localhost:5000/api/routeX',
                data: {
                    hasHeader: false
                },
```

I have 2 issues:
1. I tried the express server example. The response returned is correct. However (even by creating manually the uploads/ folder in a folder with writing permissions) **no file is stored**
2. I can't figure out how to actually receive the **data** (hasHeader etc.)  when sent together with the file. There is no example to this regards backend-side. I dived into the module's source code, but seems data is not pushed to the formdata being uploaded.

Thanks in advance

**Comment by dragGH102** [comment]
As for the Express server I solved.

however I don't really see how the **data** field is used (it's assigned but **never used** in the source code)
To allow me to send me both the file and the payload I modified the following:

```
ng2-uploader/.../ng2-uploader.js @ Ng2Uploader.prototype.uploadFile  [v. 0.5.6]
-->                   
form.append("file", file, file.name); # rename this.fieldName to "file"
form.append("payload", JSON.stringify(this.data)); # add
```

**Comment by andershagebakken** [comment]
I am using the formidable module in my node backend with express, and the module allows me to get the data field as such: 
`var form = new formidable.IncomingForm();
form.uploadDir = UPLOAD_DIR;
form.parse(req, function(err, fields, files) {
  // files: uploaded files
  // fields: this is where the data field is
});`
