### ISSUE TITLE
problem with file upload

### ISSUE THREAD

**Issue by lucamorelli** [bleenco/ngx-uploader#105]
trying to upload a file to an asp.net web app I obtain this error message

`An unhandled exception has occurred while executing the request System.IO.InvalidDataException: Missing content-type boundary.`

I compared two my app, one using angular 1 and one using angular 2 using chrome tools.
the angular component send this **Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryXAIXdwxDD9DS3PsV** and it works,
the angular2 component send **Content-Type:multipart/form-data** and doesn't work ( according chrome tools)
How can I fix it?

**Comment by jkuri** [comment]
this is a problem with the backend server, not this module I guess. Otherwise you can set custom headers also. Please check the docs.

**Comment by lucamorelli** [comment]
looks like there is a potential issue if I change the custome header of content type, the boundary is not added after the content-type itself.
