### ISSUE TITLE
Pure client side upload

### ISSUE THREAD

**Issue by natcohen** [bleenco/ngx-uploader#106]
Currently the file upload is exclusively handled by the server (you need to provide the option.url).

I'm looking for a simple solution to send the file(s) to the function so I could use [FileReader](https://developer.mozilla.org/en/docs/Web/API/FileReader) to process the file. I don't want to call any URL... Modern browsers support local databases that can store files and that use case is very common!

**Comment by gethinoakes** [comment]
+1
