### ISSUE TITLE
Problem with using both ngFileDrop and ngFileSelect

### ISSUE THREAD

**Issue by nhatdq1810** [bleenco/ngx-uploader#108]
Hi, I put ngFileDrop inside a div and ngFileSelect inside an input with type file. When I open dialog to choose file from ngFileSelect, I also want to drag a file in that dialog to div ngFileDrop too, but when I drag a file to that div, Chrome always stops working.

Is there another way to open file chosen dialog from ngFileDrop ? I have used input tag with ngFileDrop, when I dbclick to open file chosen dialog and drag a file, the dialog is not closed, I have to click cancle or open button.

**Comment by suplik10** [comment]
Hi, 
I have the similar problem. When I want use ngFileSelect input inside div of ngFileDrop I got the following exception (autoload true):
`<div class="column is-2 drag-and-drop-container" #cdire ngFileDrop 
     [options]="basicOptions"
     [events]="events"
     (onUpload)="handleUpload($event)"
     (drop)="handleDragLeave($event)">
          <label class="upload-button ">
            <input  class="hidden" type="file" 
              ngFileSelect
              [options]="basicOptions" 
              (onUpload)="handleUpload($event)">
              {{this.fileName ? this.fileName : "SELECT FILE OR DRAG AND DROP"}} 
          </label>
</div>`

Exception:
`error_handler.js:47 ORIGINAL EXCEPTION: Cannot convert undefined or null to objectErrorHandler.handleError @ error_handler.js:47
next @ application_ref.js:273
schedulerFn @ async.js:82
SafeSubscriber.__tryOrUnsub @ Subscriber.js:223
SafeSubscriber.next @ Subscriber.js:172
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:74
onError @ ng_zone.js:120
onHandleError @ ng_zone_impl.js:64
ZoneDelegate.handleError @ zone.js:207
Zone.runGuarded @ zone.js:113
NgZoneImpl.runInnerGuarded @ ng_zone_impl.js:72
NgZone.runGuarded @ ng_zone.js:236
outsideHandler @ dom_events.js:26
ZoneDelegate.invokeTask @ zone.js:236
Zone.runTask @ zone.js:136
ZoneTask.invoke @ zone.js:304`
