### ISSUE TITLE
how do you handle errors from the server?

### ISSUE THREAD

**Issue by maleck13** [bleenco/ngx-uploader#110]
Hey enjoying using your library. But having trouble finding out about an error. For example, if my server returns a 401 how do I get notified of that error?

**Comment by jkuri** [comment]
hey. thanks for the heads up. you should get response with 401, debug response. if you don't get correct status code back may be a problem with your api server, I believe.

**Comment by tanvirshuvo** [comment]
Hello jkuri. How can I do catch the response and use it to redirect, or pass it in a component?

**Comment by LukeHartcher** [comment]
Hi @jkuri I have the same issue. I can see that if I set the onFinished function I can see the 401 but Im am "outside" the angular 2 component at this point. Is there some other even that can be hooked into so we can process a 401 (or whatever) response within the angular 2 component? Also, at this point the handleUpload does not have the error flag set and progress is set to 100 even though nothing happened.

**Comment by LukeHartcher** [comment]
To get around this I had to remove specifially setting the onFinished (as this causes the response not be returned in handleUpload) and then in handleUpload check for an empty response.
