### ISSUE TITLE
Handle multiple (different) file upload

### ISSUE THREAD

**Issue by shafihuzaib** [bleenco/ngx-uploader#112]
I have a form which has **two** `file` fields, one for logo and other for a `pdf` document. Would it be possible to upload such a form in one go?

```
 <form>
     <input type="file" ngFileSelect....  //name=logo
     <input type="file" ngFileSelect....  //name=document
  </form>
```

**Comment by jainvishal520** [comment]
Have you been able to implement this? If yes then can you please provide some code or idea?
