### ISSUE TITLE
allowedExtensions does not work for ngFileDrop

### ISSUE THREAD

**Issue by schwamster** [bleenco/ngx-uploader#116]
works fine for ngFileSelect, but not for ngFileDrop. Am i doing anything wrong or is that just not supported yet?
example:

controller:
`
...
this.options = {
            url: '/api/upload',
            filterExtensions: true,
            allowedExtensions: ['image/png', 'image/jpg']
        };
...
`
template:

``` html
<div class="input-group">
                <label class="input-group-btn">
                    <span class="btn btn-primary btn-file">Browse</span>
                    <input type="file" style="display: none;"
                           ngFileSelect
                           **[options]="options"**
                           (onUpload)="handleUpload($event)" multiple>
                </label>

                <input type="text" class="form-control" placeholder="Drop files here" readonly="" 
                       ngFileDrop
                       **[options]="options"**
                       (onUpload)="handleUpload($event)"
                       [ngClass]="{'file-over': hasBaseDropZoneOver}"
                       (onFileOver)="fileOverBase($event)">
            </div>

```

**Comment by Buyomer** [comment]
I'm having same problem.

**Comment by JoaoSaleiro** [comment]
Same here...

**Comment by FilipeQ** [comment]
+1

**Comment by Scipionh** [comment]
+1

**Comment by galaxyaurona** [comment]
A quick fix solution would be copying the content of function `@HostListener('change') onChange(): void ` 
into   c
this.el.nativeElement.addEventListener('drop', (e: any) => {
      e.stopPropagation();
      e.preventDefault();
      this.onFileDrop.emit(true);
      this.files = Array.from(e.dataTransfer.files);
      this.filteringProcess();
      if (this.files.length) {
        this.uploader.addFilesToQueue(this.files);
      }
    }, false);
`
inside ng-file-drop.ts directive

**Comment by saravanakumargn** [comment]
I just tried to fix this like below and Its working for me

in my options
~~~
filterExtensions: true,
allowedExtensions: ['txt'],
~~~

and validate the file extension before upload event
~~~
beforeUpload(uploadingFile): void {
	var fileExt = uploadingFile.originalName.split('.').pop();
	let isValidFileExt = false;
	this.options.allowedExtensions.forEach(element => {
		if(fileExt == element) {
			isValidFileExt = true;
		}
	});
	if(!isValidFileExt) {
		uploadingFile.setAbort();
		console.log('Unsupported file type');
	}
}	
~~~
