### ISSUE TITLE
Complete example for Multiple File Upload

### ISSUE THREAD

**Issue by kiran-vadla** [bleenco/ngx-uploader#127]
Hi @jkuri , 

We were trying the sample application of 'Multiple File Upload' referring sample code from the Documentation (http://ng2-uploader.com/docs#multiple) and found that the sample snippet provided doesn't work . We were looking for complete and correct source for the examples provided in the documentation of this package 'ng2-uploader'. Appreciate if you can provide the link to the source or the actual source for the same at the earliest possible . 

Thanks,
Kiran.

**Comment by kiran-vadla** [comment]
Just like that addressed @jkuri in the above issue . Appreciate response from any of the other contributors also .

**Comment by apiweb** [comment]
Same problem here :(
