### ISSUE TITLE
'multiple'=false options don't work

### ISSUE THREAD

**Issue by NGizdov** [bleenco/ngx-uploader#131]
As far as I see there is no implementation if you set 'multiple' to false, if you want to upload only one file (the last chosen one).

**Comment by jkuri** [comment]
this is default.

**Comment by alex88** [comment]
does it works with true? from what I've seen, user can select just one element at time

**Comment by jkuri** [comment]
hey. last time I tried `<input type="file" name="file" multiple>` it worked.

**Comment by alex88** [comment]
Oh, right, I thought I just had to set it into the options :/
