### ISSUE TITLE
Options DataBinding

### ISSUE THREAD

**Issue by JesusMayuri7** [bleenco/ngx-uploader#133]
Please an example of adding data to options after OnInit or DataBinding NgModel

 this.options = {
      url: 'http://api.ng2-uploader.com:10050/upload',
      filterExtensions: true,
      allowedExtensions: ['image/png', 'image/jpg'],
      calculateSpeed: true,
      data: {
        userId: this.user,
        isAdmin: this.user
      },      
    };

  this.options.data = { userId: this.user }  ????

**Comment by KirilVelichkov** [comment]
i have the same issue. Why is no one answering :/

**Comment by nikgavalas** [comment]
Same issue here as well. I can't seem to change the data. I even bound the data to another object which I would have thought would fix it through referencing but it didn't. Any ideas?

**Comment by jkuri** [comment]
Did you try new version 2.0.0?

**Comment by nikgavalas** [comment]
I just tried that. I get the exception 'EXCEPTION: _this.files.filter is not a function'. Am I missing a dependency?

**Comment by jkuri** [comment]
Try disable filter extensions.

**Comment by nikgavalas** [comment]
Didn't seem to fix it for me. 

`	ngOnInit() {
		this.options = {
			url: `${this.apiUrl}/api/public/upload`,
			data: this.uploadData,
			filterExtensions: false,
			authToken: this.userService.getAuthHeader(),
			authTokenPrefix: ''
		};
	}`

I have also tried setting the options again in beforeUpload

`	beforeUpload(uploadingFile): void {
		this.options = {
			url: `${this.apiUrl}/api/public/upload`,
			data: this.uploadData,
			filterExtensions: false,
			authToken: this.userService.getAuthHeader(),
			authTokenPrefix: ''
		};`

**Comment by p-engelkes** [comment]
I encounter the same error. Setting filterExtensions to false did not fix this problem for me either.

**Comment by milenkovic** [comment]
Same here. Changing data before uploading image would be great.

**Comment by milenkovic** [comment]
I found hack for setting data, you can put function on (mouseenter) and set data before clicking.

HTML:
`<label for="upload" (mouseenter)="setData()">
	<input type="file"
		   accept="image/*"
		   class="upload-image-input"
		   id="upload"
		   name="upload"
		   ngFileSelect
		   [options]="options"
		   [events]="uploadEvents"
		   (onUpload)="handleUpload($event, question)"
		   hidden>
</label>`

TS:
`setData() {
	this.options.data = {
		prop1: 'value1'
	};
}`

**Comment by davePlug** [comment]
@jkuri I'm still having the same issue @JesusMayuri7 explained.
Any news on this?
