### ISSUE TITLE
Upload a file on Button click

### ISSUE THREAD

**Issue by kirantodupunoori** [bleenco/ngx-uploader#135]
Hi,

I am using this ng2-uploader. Currently it uploads file to server as soon as we browse and choose a file, however my requirement is to upload the file when user clicks on upload button instead of "Choose file". Is there a way that I can make this change for my application.

**Comment by Chesteer89** [comment]
It's simple. Just add option for your uploader:
`this.options = {
   ...
   autoUpload: false,
   ...
}`

register events emitter and add method to handle manual upload:
`private events: EventEmitter<any> = new EventEmitter();`
`startUpload() {
        this.events.emit('startUpload');
    }`

modify your html:
`<input type="file" 
                  ngFileSelect
                  [options]="opts" 
                  [events]="events"
                 ...>`

and just call it with your 
`<button (click)="startUpload()" />

**Comment by Chyngyz** [comment]
Hi,
How do you show the details about the selected file? Especially it is valuable to show selected file details in the scenarios like above.

**Comment by rrubio** [comment]
Hi Guys,

I'm trying to implement manual load too, followed the instructions above with no luck. It's as though the flag gets ignored. As per code examples, i've followed the advanced method.

On the template i have the following:

`                                            <div class="col-md-3">
                                                  <input type="file"
                                                        ngFileSelect
                                                        [options]="options"
                                                        [events]="events"
                                                        (onUpload)="handleUpload($event)"
                                                        (beforeUpload)="beforeUpload($event)">
                                            </div>
`

and on the component: 

`ngOnInit() {
    this.zone = new NgZone({ enableLongStackTrace: false });

    this.options = {
        url: URL,
        autoUpload: false,
        allowedExtensions: ['image/png', 'image/jpg'],
        previewUrl: 'true',
        customHeaders: {
          'custom-header': 'value'
        }
      };
  }
`

**Comment by jkuri** [comment]
@rrubio you need to emit `startUpload` event to module input `[events]`.

**Comment by rrubio** [comment]
@jkuri thank you for your quick response, much appreciated. Sorry about this, but i don't think i follow what you mean.

**Comment by jkuri** [comment]
@rrubio try something like this:

```ts
uploadEvents: EventEmitter = new EventEmitter()<any>;

uploadButton() {
  this.uploadEvents.emit('startUpload');
}
```

```html
<input type="file" ngFileSelect [options]="opts" [events]="uploadEvents">
```

just as @Chyngyz suggested.

**Comment by rrubio** [comment]
@jkuri thank you man!

**Comment by sansicruxer** [comment]
Hi i am trying to upload file using ngx uploader but i am getting Unexpected value 'NgFileSelect' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation. even though i am doing the same code as mentioned.please help me. Thank you
