### ISSUE TITLE
Compilation error after latest update

### ISSUE THREAD

**Issue by ChristmasFish** [bleenco/ngx-uploader#143]
node_modules/ng2-uploader/src/services/ng2-uploader.ts(87,3): error TS2322: Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<UploadedFile>'.
  Type '{}' is not assignable to type 'UploadedFile'.
    Property 'id' is missing in type '{}'.

Latest working version I checked is 1.5.3
Typescript version 2.0.10

**Comment by jkuri** [comment]
@ChristmasFish thanks for posting an issue. can you make a pr maybe?
