### ISSUE TITLE
What is the url referring to?

### ISSUE THREAD

**Issue by cenjennifer** [bleenco/ngx-uploader#144]
Hi - Can you explain what url the required 'url' parameter is referring to? Where is the uploaded file stored to? Is the file uploaded stored locally on the page or does it have to hit an api to store the uploaded file (even if it's before submission)?

Thanks!

**Comment by jkuri** [comment]
Hi @cenjennifer, the required url is referring to backed API server. The file needs to hit an api to store the uploaded file.

**Comment by saravanakumargn** [comment]
Url in angular2 client side is
~~~
this.options = {
	url: 'http://localhost/fileupload.php,
	customHeaders: {
		   'x-csrf-token': window['CSRF']
	},
};
~~~
