### ISSUE TITLE
Mobile Uploading

### ISSUE THREAD

**Issue by Oleh-Pashchenko** [bleenco/ngx-uploader#145]
I using the Angular 2 with nodejs exress app and followed the examples they are working well on web but doesn't works on iPad and my samsung phone, can you help me to resolve it?

**Comment by lukasz-galka** [comment]
@Oleh-Pashchenko Do you still have this issue? I have checked on Ipad Air (a1474) and on Galaxy Tab S2 and everything is working fine.
