### ISSUE TITLE
NgZone response never set

### ISSUE THREAD

**Issue by ventr1x** [bleenco/ngx-uploader#153]
Using just the advanced example. How do you access the response?
Every event on ngzone stops on "percent: 100, done: false" with no response delivered.
The response gets set (only seeing that with output in a template), but I'm unable to track the actual  done/finish state.
Shouldn't for example ngzone's onStable be fired after it is actually done?

**Comment by kohenj** [comment]
Facing the same issue, data.response is never set.
handleUpload is fired once, percentage is at 100, 'done' is false and handleUpload is never called again.

Server is correctly returning a HTTP 200 with custom response with the newly uploaded filename.
Have you found anything?

**Comment by alv3n** [comment]
@ventr1x @kohenj check if something in your project don't do something with `XMLHttpRequest`. In my case it was pacejs blocking it.

**Comment by kohenj** [comment]
It was exactly the same issue for me, pacejs has been overriding it. Maybe it will others!

**Comment by kurtuluso** [comment]
pace.js was overriding XMLHttpRequest. I fixed it but now it SOMETIMES trigger handleUpload.
No problem during progress but when the upload is finished, last emitter SOMETIMES can not run handleUpload.
Couldn't find a solution
