### ISSUE TITLE
auth token example ?

### ISSUE THREAD

**Issue by daslicht** [bleenco/ngx-uploader#155]
Hi, 
is there somewhere an example how to use the auth token ?
Or is it just a string which i have to manually compare on the server, such as as firebase token ?

~ Marc

**Comment by saravanakumargn** [comment]
You can do something like this..

~~~
this.options = {
	url: 'http://localhost/fileupload.php,
	customHeaders: {
		   'x-csrf-token': window['CSRF']
	},
};
~~~

**Comment by OnlyBelter** [comment]
How can I pass `this.options` to `UploadInput` ?
