### ISSUE TITLE
ng2-uploader with Angular 2 & .net core

### ISSUE THREAD

**Issue by mkarmani** [bleenco/ngx-uploader#156]
Hi, Want to know if it's possible to have a basic use of ng2-uploader with .net core server side?
I have this issue: 
http://stackoverflow.com/questions/41147638/upload-a-file-with-ng2-uploader-angular2-net-core

Thank u in advance.

**Comment by Sn3b** [comment]
I just posted a "possible answer" to stackoverflow. I just run into this issue but it was because the "uploads" folder didn't exist on my backend (C:\Sources\MySolution\trunk\src\MyProject\wwwroot\uploads)
