### ISSUE TITLE
Can't bind to 'options' since it isn't a known property of 'input'.

### ISSUE THREAD

**Issue by Partovic** [bleenco/ngx-uploader#158]
Hi,

still got this error.
installed your module via "npm install ng2-uploader".
Do I have to update the sources manually?

**Comment by LukasSefcik** [comment]
I have same problem.

**Comment by narainsagar** [comment]
I guess this kind of error occurs when you don't include angular FormsModule into your app module.
and add under your module `imports`.

```
// app.module.ts
import {FormsModule} from '@angular/forms';
import {CommonModule} from '@angular/common';
import { Ng2UploaderModule } from 'ng2-uploader';
...
@NgModule({
  ...
  imports: [
   .....
   FormsModule,
   CommonModule,
    Ng2UploaderModule,
    .....
  ],
  ...
})
```

Please verify & give some more details.

Thanks, 
Cheers,

**Comment by AdrianPasalega** [comment]
I think the problem is regarding the version of  typescript you use to compile it. I used the IDE compiler (typescript version 1.8.10) and I didn't get the error, and after i switch and compile it with gulp-typescript ( "typescript": "^2.0.2" ) i got the same error as above. Maybe the new typescript has issues with the way the 'options' input is set.

**Comment by LudovicE07** [comment]
Hi, i've got error too. No problem with new project, but project with avdanced template i've got this error, do you have any idea?

Thanks you

**Comment by jkon** [comment]
I am having this problem too. I'm using typescript 2.0.3. I can't go back to 1.8.10 though or else other stuff starts breaking in my build. Is there another way around this?

**Comment by AdrianPasalega** [comment]
Hi, we can modify the 'options' input and use OnChanges and it should work, i can try to make a pull request on monday, and maybe it helps.

**Comment by jkuri** [comment]
hey guys. this should work already, just tried like this:
```ts
this.options = new NgUploaderOptions({
   url: 'http://api.ngx-uploader.com/upload',
   autoUpload: true,
  calculateSpeed: true
});

setTimeout(() => {
  this.options = new NgUploaderOptions({
    url: 'http://api.ngx-uploader.com/upload',
    autoUpload: true,
    calculateSpeed: true
  });
}, 2500);
```

and it works.

**Comment by jkon** [comment]
@jkuri where are you putting that? It doesn't seem to work for me, but I'm not sure if I have it in the right place. Can you show it inside the basic example component?

**Comment by jkuri** [comment]
inside `constructor()`.

**Comment by jkon** [comment]
That doesn't work for me. Still get the can't bind error.

**Comment by jkon** [comment]
what typescript version are you using?

**Comment by jkuri** [comment]
`2.0.10`. are you using SystemJS? if so, check your network tab in google chrome dev tools if ng2-uploader.js gets properly loaded.

**Comment by jkon** [comment]
I'm using webpack

**Comment by jkon** [comment]
I looked at the network traffic and inspected the chunk.js for the page that has the uploader and I found this: var ngx_uploader_1 = __webpack_require__(1524);
I'm guessing that is where the uploader package is included

**Comment by jkuri** [comment]
yes I guess so. can you share your code and I'll check where is the problem.

**Comment by jkon** [comment]
Module:
`/**
 * Created by joshua on 1/6/17.
 */
import {NgModule}      from '@angular/core';
import {CommonModule}  from '@angular/common';

import {routing}       from './imageUploader.routing';
import {NgaModule} from '../theme/nga.module';
import {FormsModule, ReactiveFormsModule} from '@angular/forms';
import {ImageUploader} from './imageUploader.component';
import {NgUploaderModule} from 'ngx-uploader';

@NgModule({
  imports: [
    CommonModule,
    NgaModule,
    FormsModule,
    ReactiveFormsModule,
    routing,
    NgUploaderModule
  ],
  declarations: [
    ImageUploader
  ]
})
export class ImageUploaderModule {
}
`
Component:
`import { Component, OnInit } from '@angular/core';
import { NgUploaderOptions } from 'ngx-uploader';

@Component({
  selector: 'image-uploader',
  template: require('./imageUploader.component.html'),
  styles: [require('./imageUploader.scss')]
})
export class ImageUploader implements OnInit {

  private url: string = 'http://localhost:8888/uploadProfilePic';
  ngOnInit(): void {

  }
  constructor() {
    
  }

  uploadFile: any;
  hasBaseDropZoneOver: boolean = false;
  options: NgUploaderOptions = {
    url: this.url
  };
  sizeLimit = 2000000;

  handleUpload(data): void {
    if (data && data.response) {
      data = JSON.parse(data.response);
      this.uploadFile = data;
    }
  }

  fileOverBase(e:any):void {
    this.hasBaseDropZoneOver = e;
  }

  beforeUpload(uploadingFile): void {
    if (uploadingFile.size > this.sizeLimit) {
      uploadingFile.setAbort();
      alert('File is too large');
    }
  }

}`

Template: 
`<input type="file"
       ngFileSelect
       [options]="options"
       (onUpload)="handleUpload($event)"
       (beforeUpload)="beforeUpload($event)">
<div>
  Response: {{ uploadFile | json }}
</div>`

Router:
`import {Routes, RouterModule}  from '@angular/router';

import {ImageUploader} from './imageUploader.component';

// noinspection TypeScriptValidateTypes
const routes: Routes = [
  {
    path: '',
    component: ImageUploader
  }
];

export const routing = RouterModule.forChild(routes);
`

**Comment by jkuri** [comment]
try to set 
```ts
options: NgUploaderOptions = {
  url: this.url
};
```
inside constructor.

**Comment by jkon** [comment]
No difference. I tried 
this:
```
constructor() {
    this.options = new NgUploaderOptions({
      url: this.url
    });
  }
```
and this:
```
constructor() {
    this.options.url = this.url;
  }
```

**Comment by jkon** [comment]
Also, I'm using "ngx-uploader": "^2.0.5",
Should I try a different version?

**Comment by jkon** [comment]
I have ng2-uploader@1.1.0 installed as well because the project template I started with had an uploader, but I couldn't get it to make the actual upload work. I had the files.forEach not a function error happening. So I decided to start one from scratch using the latest version of ngx-uploader

**Comment by jkuri** [comment]
no, version is okay. that is interesting, can you try to import from `ngx-uploader/ngx-uploader';`. 
Here is demo page if helps you with anything:
[ngx-uploader.com.zip](https://github.com/jkuri/ngx-uploader/files/691567/ngx-uploader.com.zip)

**Comment by jkon** [comment]
That didn't work either :( 
I'll take a look at the demo and see if I can glean anything useful

**Comment by LudovicE07** [comment]
Hi, thanks for you help. I've got ngx-uploader: 2.0.3
I have try to add your demo in my project bit still have error:
Can't bind to 'options' since it isn't a known property of 'div'.

Here is my dependencie. Thanks

> "dependencies": {
    "@angular/common": "2.4.1",
    "@angular/compiler": "2.4.1",
    "@angular/core": "2.4.1",
    "@angular/forms": "2.4.1",
    "@angular/http": "2.4.1",
    "@angular/platform-browser": "2.4.1",
    "@angular/platform-browser-dynamic": "2.4.1",
    "@angular/router": "3.4.1",
    "@angular/upgrade": "2.4.1",
    "@types/lodash": "4.14.44",
    "angular-calendar": "0.6.0",
    "angular2-datatable": "0.5.2",
    "angular2-ladda": "^1.0.6",
    "angular2-toaster": "2.0.0",
    "chart.js": "^2.3.0",
    "core-js": "^2.4.0",
    "dragula": "^3.7.2",
    "moment": "2.17.1",
    "ng2-bootstrap": "^1.1.16-10",
    "ng2-charts": "^1.4.4",
    "ng2-dragula": "^1.2.2",
    "ng2-file-upload": "^1.1.4-2",
    "ng2-select": "^1.1.2",
    "ng2-translate": "^4.2.0",
    "ngx-uploader": "^2.0.3",
    "rxjs": "5.0.2",
    "ts-helpers": "^1.1.2",
    "zone.js": "0.7.4"
  },
  "devDependencies": {
    "@types/jasmine": "^2.5.37",
    "angular-cli": "1.0.0-beta.21",
    "codelyzer": "2.0.0-beta.4",
    "jasmine-core": "^2.5.2",
    "jasmine-spec-reporter": "2.7.0",
    "karma": "1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-jasmine": "^1.1.0",
    "karma-remap-istanbul": "^0.4.0",
    "protractor": "4.0.14",
    "ts-node": "1.7.3",
    "tslint": "4.2.0",
    "typescript": "2.1.1"
  }

**Comment by ivanovmv90** [comment]
Solved this by adding NgUploaderModule to exports:
```
@NgModule({
    imports: [
        BrowserModule,
        FormsModule,
        NgUploaderModule,
        SelectButtonModule
    ],
    declarations: [FORM_COMPONENTS],
    exports: [FORM_COMPONENTS, NgUploaderModule]
})
export class SomeModule {}
```

**Comment by trueflywood** [comment]
Hi,

still got this error.
installed your module via "npm install ngx-uploader".

**Comment by LudovicE07** [comment]
Hi still got this error and I can't continue my interface without upload file solution... Do you have any idea how fix this?

Thaks you,

**Comment by dongtong** [comment]
I have the same error, anyone could solve it?
