### ISSUE TITLE
How to set data property after image is selected

### ISSUE THREAD

**Issue by KirilVelichkov** [bleenco/ngx-uploader#161]
Hi 

I need to select the opstions.data property values after i select my image.
This seems impossible for now.

For example i have
options = {
data:{
 title: 'same value that i need to add from a text field'
}
}

Any solutions?

**Comment by milenkovic** [comment]
@KirilVelichkov 
https://github.com/jkuri/ngx-uploader/issues/133#issuecomment-272411799
