### ISSUE TITLE
Multiple File Uploader instances on same page/template fires "onUpload", "onFileOver" "beforeUpload" multiple times

### ISSUE THREAD

**Issue by suryakand** [bleenco/ngx-uploader#163]
Let's say I want to upload multiple files using different file uploader instance on same page and if I created multiple uploader instances on same page/template then events like "onUpload", "onFileOver" "beforeUpload" fires  multiple times.

Is there a way to restrict events being listened by own instance of uploader that was used to upload the file?

**Comment by kiwileaks78** [comment]
I have exactly the same issue here ... I use three <input ngFileSelect ...> on the same page. This was working well on previous versions of ng2-uploader (1.2.0), but now (onUpload) event fires multiple times (one time for each <input ngFileSelect> on the same page ... 

I had to revert to ng2-uploader 1.2.0 to fix the problem. It also fixed the #164 issue.

**Comment by naveedahmed1** [comment]
@suryakand can you check if your issue is also due to the reason I mentioned in 
https://github.com/jkuri/ngx-uploader/issues/173 ?

You can confirm it by removing the NgUploaderService from providers list of NgUploaderModule and add it to the providers list of NgFileSelectDirective.

**Comment by norenma** [comment]
I also have this issue. I use a file-upload in a ngFor, and it always runs handleUpload on only this first instance.

**Comment by naveedahmed1** [comment]
@norenma  please have a look at https://github.com/jkuri/ngx-uploader/issues/173#issuecomment-271111255

**Comment by lukefarran** [comment]
I'm having the same issue. I did: "You can confirm it by removing the NgUploaderService from providers list of NgUploaderModule and add it to the providers list of NgFileSelectDirective." and it fixed the issue.  Is there an ETA for this fix or would it help if I submitted a PR? Thanks!

**Comment by michaelkariv** [comment]
[newcomer] can anyone provide a sample on how to have multiple uploads  now that the bug has been  fixed?

**Comment by jainvishal520** [comment]
Can anybody provide code sample for multiple uploads on same page?

**Comment by xts-velkumars** [comment]
Any sample code ?

**Comment by momargoh** [comment]
I still get an error with the ngFileSelect directive when I have multiple in a component: only the first one gets fired.

My .component.html has... 
```
<app-file-upload (upload)="onUploadFile($event, 'first-uploader')"></app-file-upload>
<app-file-upload (upload)="onUploadFile($event, 'second-uploader')"></app-file-upload>
```

My FileUploadComponent is basically just the template in the README...
```
<div
    class="drop-container"
    ngFileDrop
    [options]="options"
    (uploadOutput)="onUploadOutput($event)"
    [uploadInput]="uploadInput"
    [ngClass]="{ 'is-drop-over': dragOver, alert: alert }"
  >
    <div *ngIf="showPreview" class="preview-wrapper">
      <div *ngIf="!previewSrc" class="img-preview-placeholder">No Image</div>
      <img
        *ngIf="previewSrc"
        [src]="previewSrc"
        alt="Preview image"
        height="100"
        class="img-preview"
      />
    </div>
    <div class="upload-info-wrapper">
      <mat-icon>upload</mat-icon>
      <div class="text-row">
        <span class="row-bold"
          >Drop your file(s) here or
          <label class="upload-button row-bold" for="files">browse</label>
          <input
            type="file"
            id="files"
            class="files"
            ngFileSelect
            [options]="options"
            [accept]="accept"
            (uploadOutput)="onUploadOutput($event)"
            [uploadInput]="uploadInput"
          />
        </span>
      </div>
      <div class="text-row row-grey">
        Supported: {{ supportedTypes }}. Max size:
        {{ maxFileSizeMB | number: "1.0-0" }}MB
      </div>
    </div>
```

So whenever I drag a file onto the drop zone I get the correct 'first-uploader'/'second-uploader' being emitted but if I click the `browse` button and use the OS file explorer I only ever get 'first-uploader' being emitted.

I am using v11.0.0 with Angular v14.1.2

**Comment by momargoh** [comment]
I just solved my issue by giving each uploader a unique `id`, so I replaced my `browse` button with 

```
<span class="row-bold"
          >Drop your file(s) here or
          <label class="upload-button row-bold" for="files{{id}}">browse</label>
          <input
            type="file"
            id="files{{id}}"
            class="files"
            ngFileSelect
            [options]="options"
            [accept]="accept"
            (uploadOutput)="onUploadOutput($event)"
            [uploadInput]="uploadInput"
          />
        </span>
```
and added `id: number = Math.random();` to my FileUploadComponent (`Math.random()` is good enough for me)
