### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by StoianStoianov** [bleenco/ngx-uploader#178]
When i start my application i receive GET http://localhost:3000/node_modules/ngx-uploader/src/classes.js 404 (Not Found).
I imported `import { NgUploaderModule } from 'ngx-uploader';` But it still runs error

**Comment by mfcar** [comment]
Same here

**Comment by Sn3b** [comment]
In the source of the compiled files (*.js) look for the references to "classes" and change them to "classes/index".

There are 3:
/node_modules/ngx-uploader/index.js (line 10)
/node_modules/ngx-uploader/src/directives/ng-file-drop.js (line 16)
/node_modules/ngx-uploader/src/directives/ng-file-select.js (line 16)

**Comment by lukefarran** [comment]
Same here
