### ISSUE TITLE
Upload method configurable?

### ISSUE THREAD

**Issue by 0r0s** [bleenco/ngx-uploader#198]
Can the uploader use PUT instead on POST? I want to use it with Amazon S3 presigned urls, which requires PUT instead of POST. http://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html

**Comment by Doehl** [comment]
As you can see in the demo at [ngx-uploader.com/advanced](http://ngx-uploader.com/advanced), yes you can. With the NgUploaderOption method: 'PUT'
