### ISSUE TITLE
Displaying file name when dropped or browsed

### ISSUE THREAD

**Issue by juanhuguetgarcia** [bleenco/ngx-uploader#200]
Hi,

I am using manual uploading and I am not able to display the filename or some indicator to let the user know that the file he selected is waiting for him to click on the submit file button. Does anyone know how to handle it?

Thanks a lot!

BTW, Nice job! @jkuri

**Comment by hsbalar** [comment]
Yes havnig same issue here,
For the moment you can do something like this to get file name,

> <input type="file"
>                  class="hidden"
>                  ngFileSelect
>                  [options]="options"
>                  [events]="inputUploadEvents"
>                  (onUpload)="handleUpload($event)"
>                  (onPreviewData)="handlePreviewData($event)"
>                  (beforeUpload)="beforeUpload($event)"
>                  (change)="onChangeFile(file.value)"
>                  #file>

In `onChangeFile(file: any)` you will get file name.

**Comment by MrCroft** [comment]
@hsbalar this only works for the input (ngFileSelect). But if the user drops files over the drop zone (ngFileDrop), there is no "drop" event for that.

Been back and forth between Angular uploaders the past couple of days, but none of them are fully functional :(

**Comment by jolle-c** [comment]
Not sure if this is still an issue. But all files added will be items in the files array. To display them iterate that array and grab the name.
`
<ul class="list-group list-group-flush">
    <li class="list-group-item" *ngFor=" let file of files">
       {{ file.name }}
    </li>
</ul>
`
