### ISSUE TITLE
[Newcomer] Explain fields in option

### ISSUE THREAD

**Issue by tups-ibl** [bleenco/ngx-uploader#215]
I'm a newcomer and I read ngx-uploader docs but I could not look for where explains option,  so I am still confused about the fields in option. Can someone explains the meaning of each field?

```
  url: string;
  cors?: boolean;
  withCredentials?: boolean;
  multiple?: boolean;
  maxUploads?: number;
  data?: any;
  autoUpload?: boolean;
  multipart?: any;
  method?: string;
  customHeaders?: any;
  encodeHeaders?: boolean;
  authTokenPrefix?: string;
  authToken?: string;
  fieldName?: string;
  fieldReset?: boolean;
  previewUrl?: boolean;
  calculateSpeed?: boolean;
  filterExtensions?: boolean;
  allowedExtensions?: string[];
```

**Comment by jkuri** [comment]
hi @phansontu. is there any field which is completely unknown how to use it? please reply and I can explain it.

**Comment by phansontu** [comment]
@jkuri 
They are maxUploads, data, withCredentials. And one more question, Have any function to get the extensions of file like: 
return extension('image.png')
and the result is 'png'
