### ISSUE TITLE
handleUpload data.response always undefined

### ISSUE THREAD

**Issue by kohenj** [bleenco/ngx-uploader#220]
Following the basic example with autoUpload set to true.
Server is correctly receiving the info and returns a HTTP 200 with a custom response including new filename.

handleUpload is only fired once with 'percent:100' and 'done:false' and 'data.response' undefined.

Do we need to follow a specific response format?
Anyone facing the same issue?

**Comment by jkuri** [comment]
try wrapping `zone.run` inside `setTimeout(() => zone.run(() => { ... }));`

**Comment by kohenj** [comment]
It is wrapped with a setTimeout unfortunatly, even tried to give it a little more time without success.
In Network DevTools I can see the correct 200 response of the POST to the server.

**Comment by jkuri** [comment]
maybe you are uploading file that small that is uploaded immediately?

-- 
Jan Kuri

**Comment by kohenj** [comment]
Good guess, but unfortunatly I've tried files > 3MB.
It is true that I am running both servers locally on different ports, it can crank up my upload speed.
My upload server is a NodeJs REST API.

**Comment by jkuri** [comment]
check if you really return json back.

**Comment by kohenj** [comment]
Confirmed, it is valid JSON sent back.
Is there a specific JSON nesting properties to follow?

**Comment by kohenj** [comment]
Not sure if this info can be helpful, but:
- recently migrated from angular RC5 to latest release
- was using ng2-uploader@0.5.14 before and switched to ngx-uploader with the migration

on ng2-uploader@0.5.14 had to change something to make it works, 
services/ng2-uploader.ts@~145 had to change:
`xhr.onreadystatechange = () => {
      if (xhr.readyState === XMLHttpRequest.DONE) `
to
`xhr.onreadystatechange = () => {
      if (xhr.readyState === 4) {`

**Comment by jkuri** [comment]
not its not a specific json to follow, not sure where's the problem honestly. if you can share the part of api upload handler i can take a look.

**Comment by kohenj** [comment]
Will do more tests to see if the way the backend returns the response has any impacts.
Will let you know, thanks for the quick responses.

In the meantime if anyone else has already face that issue, let us know.

**Comment by kohenj** [comment]
I've tested forcing my upload server (python server using Flask) to return a full response:
`
        resp_data = {
            'status': status,
            'msg': msg,
            'data': { 'originalName': original_file_name, 'generatedName': filename }
        }`
`        resp = make_response(json.dumps(resp_data), return_code)`
`        resp.headers['Content-Type'] = 'application/json'`
`        return resp`

on the client side, the handleUpload:
` handleUpload(data: any): void {`
`    setTimeout(() => {`
`      this.zone.run(() => {`
`        this.response = data;`
`        console.info(data, data.response);`
`        if (data && data.response) {`
`          this.response = JSON.parse(data.response);`
`        }`
`      });`
`    });`
`}`

and here the response from the DevTool:
![image](https://cloud.githubusercontent.com/assets/3468956/23387504/ed68242a-fd2a-11e6-8718-22acbb863bb3.png)
![image](https://cloud.githubusercontent.com/assets/3468956/23387518/056a7e7e-fd2b-11e6-9de0-3778fe2d9fc7.png)
![image](https://cloud.githubusercontent.com/assets/3468956/23387567/65a3af36-fd2b-11e6-94e6-838e497e7ccc.png)

Always getting `data.response` undefined. I don't get it :/

**Comment by kohenj** [comment]
Ok, I found the problem with my issue, it is with this line in _services/ngx-uploader.ts@91_:
`if (xhr.readyState === XMLHttpRequest.DONE) `

For some reason, on my side, `XMLHttpRequest.DONE` does not return `4` but instead `function removeEventListener() { [native code] }`.

But `XMLHttpRequest().DONE` does return `4`. I guess it's mostly a problem on my side, still trying to figure out why.

**Comment by inshaf** [comment]
im having the same issue... handleUpload is only fired once with 'percent:100' and 'done:false' and 'data.response' undefined.
im using laravel as the back end... Any idea how to fix this ?

**Comment by inshaf** [comment]
at "NgUploaderService" class, "if (xhr.readyState === XMLHttpRequest.DONE)" condition fails on "onreadystatechange". But if i put condition as (xhr.readyState === 4) then it is working as expected. I can continue with this condition. But why "(xhr.readyState === XMLHttpRequest.DONE)" is not working ?
