### ISSUE TITLE
[Newcomer] Attaching the proper headers for Google Storage "Simple Upload"

### ISSUE THREAD

**Issue by donjae** [bleenco/ngx-uploader#221]
(Sorry in advanced for the basic question)

For google's storage direct uploads, it requires the following format of the headers: 

```
POST https://www.googleapis.com/upload/storage/v1/b/myBucket/o?uploadType=media&name=myObject HTTP/1.1
Content-Type: image/jpeg
Content-Length: [NUMBER_OF_BYTES_IN_FILE]
Authorization: Bearer [YOUR_AUTH_TOKEN]
```

I can get the 'Content-Length' from `UploadingFile.size` which is the object property created through this module, but not sure how to retrieve the mime-type/content-type property for the file thats selected. Does anybody know?

[More info on google's direct storage http requests](https://cloud.google.com/storage/docs/json_api/v1/how-tos/simple-upload)

**Comment by uncledent** [comment]
Change options to:
multipart: false
Hope this helps

**Comment by retailify** [comment]
outdated (prior release 3.x)
