### ISSUE TITLE
Extensions not filtered

### ISSUE THREAD

**Issue by trueflywood** [bleenco/ngx-uploader#224]
Extensions not filtered when autoUpload: true,

**Comment by lukasz-galka** [comment]
I have checked all your bugs #222 #223 #224 and everything is working fine for me. Could you give more info?

**Comment by trueflywood** [comment]
#222 could not be reproduced. Perhaps after reinstalling packages.

#223, #224 

options:
`
this.options = new NgUploaderOptions({
            filterExtensions: true,
            allowedExtensions: ['jpg', 'png'],
            url: this.backendService.serveUrl + 'api/units/' + this.id + '/photo',
            authToken: this.cookieService.get('access_token'),
            fieldName: 'content'
        });
`

HTML:
`<div class="image" >
                            <div class="drag-n-drop-container"
                                 ngFileDrop
                                 [options] = "options"
                                 [events]="inputUploadEvents"
                                 (onUpload)="handleUpload($event)"
                                 [ngClass]="{'file-over': hasBaseDropZoneOver}"
                                 (onFileOver)="fileOverBase($event)"
                                 (beforeUpload)="beforeUpload($event)"
                                 (onUploadRejected)="handleUploadRejected($event)">
                                <label class="upload-button">
                                    <input type="file"
                                           class="hidden"
                                           ngFileSelect
                                           [options] = "options"
                                           (onUpload)="handleUpload($event)">
                                    +
                                </label>
                            </div>
                        </div>`

the function "**handleUploadRejected**" not called and file upload to server.


if **autoUpload: false,** and start downloading via events,  file with restricted extensions are not loaded.
The function "**handleUploadRejected**" not called.

**Comment by lukasz-galka** [comment]
you are right, I was checking ngFileSelect

**Comment by charbonnier666** [comment]
still doesn't works with 2.2.5 ( I try with file zip but browse not filtered (all extension) and I can upload anything)

**Comment by charbonnier666** [comment]
Edit: it doesn't upload not-zip files but it doesn't filter in browse

**Comment by scottlepp** [comment]
@charbonnier666 you can just use the "accept" attribute on the input tag:  https://www.w3schools.com/tags/att_input_accept.asp
