### ISSUE TITLE
Java Rest end point - Required CommonsMultipartFile parameter 'image' is not present

### ISSUE THREAD

**Issue by liyakhatalikhan** [bleenco/ngx-uploader#235]
Getting this error when the java rest endpoint is receiving the request .

  @PostMapping("/avatarImage")
    @Timed
    public ResponseEntity<ImageDTO> avatarImage(@RequestParam(value = "image") CommonsMultipartFile file) throws URISyntaxException {
        
I tried changing the requestparam to file but it doesnot work.

I tried removing the requestparam, then i get 
[org.springframework.web.multipart.commons.CommonsMultipartFile]: No default constructor found;

**Comment by osahner** [comment]
the [default param name is file](https://github.com/jkuri/ngx-uploader/blob/master/src/classes/ng-uploader-options.class.ts#L67). so try
```java
@RequestParam(value="file")
```
or change the option.
```typescript
new NgUploaderOptions({
  fieldName: 'image'
});
```
