### ISSUE TITLE
how to use Promise with ngx-uploader

### ISSUE THREAD

**Issue by noface151151** [bleenco/ngx-uploader#238]
I have two component: component A and component B
Component B using ngx-uploader with selector "upload-file".
Component A use selector "upload-file" .
In Component B i have function:
 startUpload() {
    this.inputUploadEvents.emit('startUpload');
  }
When click button in component A, i want to upload file. I use ViewChild in component A and it succeeded, but i want to click button in component A ->upload file -> receiving response(use EventEmitter to get response from component B ) -> use response  to do something  in component A, but response i receive always null, i checked  response in component B and it not null when Upload Completed, I think that is due to the asynchronous. Here my code in comonent A:
  @ViewChild(BaPictureUploader)
    private baPictureUploader: BaPictureUploader;
    .....
     UploadCompleted(message) {   //use EventEmitter 
        this.ResponseUpLoadImage = message;
        console.log( this.ResponseUpLoadImage)  //not null
    }
     
    click():void{
        this.baPictureUploader.startUpload(); // call  startUpload() from component B
         console.log(this.ResponseUpLoadImage)   // always null
    }
How to upload a file before then to do something (write response log  for example). It is possible to convert to a promise ?

**Comment by modeh13** [comment]
Hi, I had same problem, I am sorry for my bag english.

HTML:
<ba-picture-uploader [defaultPicture]="defaultPicture" 
   [uploaderOptions]="uploaderOptions" **(onUploadCompleted)="uploadCompled($event)"**> 
</ba-picture-uploader>

Typescript:

uploadCompled(output: UploadOutput) {
 // ... This event will execute after upload file, and You can check properties "output" for evalue if file was upload success or not.
}

Hope, I helped you.
