### ISSUE TITLE
Setting withCredentials flag

### ISSUE THREAD

**Issue by AndreasGassmann** [bleenco/ngx-uploader#277]
It seems that in v3 there is no way to set the xhr `withCredentials`-flag. Is this intentional or was it removed by accident? Without it the browser does not send our httpOnly session to the server and can therefore not be authenticated.

**Comment by jkuri** [comment]
hi Andreas. its by accident, but you can still set custom headers.

**Comment by AndreasGassmann** [comment]
Thanks for the quick reply. I think you cannot set the withCredentials flag as a custom header, so we had to revert to v2 in this project. I'm packed with work currently, so I don't have time to open a PR, but maybe if things cool down I can give it a shot.

**Comment by jkuri** [comment]
that would be great, thanks.

**Comment by lunanigra** [comment]
We are also using v3 and require the withCredentials flag.
I would really appreciate if there would a solution soon. Any kind of workaround is welcome as well.

**Comment by jkuri** [comment]
okay I will implement a solution now.

-- 
Jan Kuri

**Comment by jkuri** [comment]
hi guys, https://github.com/jkuri/ngx-uploader/commit/d255ef180f15d9b140192b724453c34653790e55 should solve the issue. can anyone give me feedback if its working? thanks.

**Comment by lunanigra** [comment]
Works! Thanks for the quick solution :smiley:

**Comment by OnlyBelter** [comment]
Anyone can give me a hint for how to set customer `headers` or `options` ? I need to set my `headers` like this:
```
    let headers = new Headers();
    headers.append('Authorization', 'JWT ' + token);
```
So I can give authentication information. Any help would be nice!

**Comment by retailify** [comment]
see Readme ;)
