### ISSUE TITLE
Filtering files by type or size

### ISSUE THREAD

**Issue by AndreasGassmann** [bleenco/ngx-uploader#278]
I'm having a hard time to filter out files by type or size. It's not exactly clear to me where I have to add that check so the file won't actually be uploaded. I copied the sample from the readme and added a simple check:

    onUploadOutput(output: UploadOutput): void {
    console.log(output); // lets output to see what's going on in the console

    if (output.type === 'cancelled') {
      return;
    }

    if (output.file) {
      console.log(output.file.type);
      if ( !output.file.type || output.file.type !== 'application/pdf' ) {
        // show toast
        this.uploadInput.emit({ type: 'cancel', id: output.file.id });
        return;
      }
    }

I assumed that this would immediately cancel the upload. But it looks like the upload is still processed and further events are emitted.

    console.js:26 Object {type: "addedToQueue", file: Object}
    console.js:26 Object {type: "allAddedToQueue"}
    console.js:26 Object {type: "start", file: Object}
    console.js:26 Object {type: "cancelled", file: Object}
    console.js:26 Object {type: "uploading", file: Object}
    // Those repeat many times depending on file size
    console.js:26 Object {type: "cancelled", file: Object}
    console.js:26 Object {type: "uploading", file: Object}
    console.js:26 Object {type: "done", file: Object}

Is there a way to hook into this process before the file upload gets started?

Thanks for your help, this library is awesome, there are just some minor things that I haven't figured out yet :)

**Comment by jkuri** [comment]
hi again :), thank you for the nice words 👍 .
If you check [here](https://github.com/jkuri/ngx-uploader/blob/master/src/ngx-uploader/classes/ngx-uploader.class.ts#L134-L148), `cancel` event actually cancels the upload which is already in progress. I think, you need something like `remove` event, but this doesn't exists currently. if you have a solution or a proposal PR is very welcome.

**Comment by josegb** [comment]
You can try to filter by extension and size with **[NgUploaderOptions](https://github.com/jkuri/ngx-uploader/tree/2.x.x)**

```
import { NgUploaderOptions } from 'ngx-uploader';

....

 public uploaderOptions: NgUploaderOptions;

....
 
  this.uploaderOptions:NgUploaderOptions = {
     url: 'http://website.com/upload' ,
     filterExtensions: true,
     allowedExtensions: ['png', 'jpg', 'jpeg'],
     maxSize: 1024 * 40,
 };
 
 ....
 
 <input type="file" ngFileSelect [options]="uploaderOptions" (uploadOutput)="onUploadOutput($event)" [uploadInput]="uploadInput" multiple>
```

**Comment by gilsdav** [comment]
It seems to work if I do this on 'addedToQueue':
        this.uploadInput.emit({
          type: 'cancel',
          id: output.file.id
        });
        **output.file.progress.status = UploadStatus.Canceled;**

**Comment by mirata** [comment]
I can cofirm what @gilsdav said. If the same file is submitted again, it doesn't get cancelled. 

Cancelling an upload that is in progress does not seem to work.

**Comment by gilsdav** [comment]
## Other solution
@AndreasGassmann with 3.1.1 fix, you can manage upload by yourself.
I personally do something like this:
```
if (output.type === 'allAddedToQueue') {
    _.each(this.files, (currentFile) => {
        if (currentFile.progress.status === UploadStatus.Queue) {
            const event: UploadInput = {
                type: 'uploadFile',
                url: this.uploadUrl,
                method: 'POST',
                file: currentFile,
                headers: BaseService.headersObject
            };
            this.uploadInput.emit(event);
        }
    });
    this.showErrorPopup();
} else if (output.type === 'addedToQueue') {
    if (this.doCheck(output.file)) {
        this.files.push(output.file); // add file to array when added
    }
}
```

**Comment by mirata** [comment]
@gilsdav - that works really well. Thanks
