### ISSUE TITLE
Failed to load /.../node_modules/ngx-uploader/tslint.json: Could not find custom rule directory: /.../node_modules/ngx-uploader/node_modules/codelyzer

### ISSUE THREAD

**Issue by webmatrixxxl** [bleenco/ngx-uploader#279]
"^2.2.8" & "^3.0.3", angular cli command 'ng lint' trows this error: 
    "tslint": "~4.5.0",

Failed to load /.../node_modules/ngx-uploader/tslint.json: Could not find custom rule directory: /.../node_modules/ngx-uploader/node_modules/codelyzer
Error
    at new FatalError (/.../node_modules/tslint/lib/error.js:40:23)
    at Object.findConfiguration (/.../node_modules/tslint/lib/configuration.js:47:15)
    at files.forEach (/.../node_modules/@angular/cli/tasks/lint.js:36:50)
    at Array.forEach (native)
    at lintConfigs.map (/.../node_modules/@angular/cli/tasks/lint.js:30:19)
    at Array.map (native)
    at Class.run (/.../node_modules/@angular/cli/tasks/lint.js:21:14)
    at Class.run (/.../node_modules/@angular/cli/commands/lint.js:45:25)
    at Class.Command.validateAndRun (/.../node_modules/@angular/cli/ember-cli/lib/models/command.js:128:15)
    at /.../node_modules/@angular/cli/ember-cli/lib/cli/cli.js:92:22

angular/cli: 1.0.6
node: 7.7.4
os: darwin x64
angular/common: 4.1.3
angular/compiler: 4.1.3
angular/core: 4.1.3
angular/forms: 4.1.3
angular/http: 4.1.3
angular/platform-browser: 4.1.3
angular/platform-browser-dynamic: 4.1.3
angular/router: 4.1.3
angular/cli: 1.0.6
angular/compiler-cli: 4.1.3

**Comment by marcoT89** [comment]
Same to me.. Any workaround?

**Comment by osahner** [comment]
Same same:

`...node_modules/ngx-uploader/tslint.json: Could not find custom rule directory: node_modules/codelyzer`

```
@angular/cli: 1.1.2
node: 6.11.0
os: darwin x64
@angular/animations: 4.2.3
@angular/common: 4.2.3
@angular/compiler: 4.2.3
@angular/core: 4.2.3
@angular/forms: 4.2.3
@angular/http: 4.2.3
@angular/platform-browser: 4.2.3
@angular/platform-browser-dynamic: 4.2.3
@angular/router: 4.2.3
@angular/cli: 1.1.2
@angular/compiler-cli: 4.2.3
@angular/language-service: 4.2.3
```

**Comment by jkuri** [comment]
did you run `npm install`? https://github.com/jkuri/ngx-uploader/blob/master/package.json#L56

**Comment by osahner** [comment]
oh yes, node_modules/codelyzer exists.

**Comment by jkuri** [comment]
ok. please try now, `3.1.1` version.

**Comment by osahner** [comment]
Hip hip!

thank you!

**Comment by jkuri** [comment]
you welcome.
