### ISSUE TITLE
unable make dynamic url for azure storage with filename in url  ngx-uploader angular2

### ISSUE THREAD

**Issue by chinna-magapu** [bleenco/ngx-uploader#280]
Hi I am implementing file upload to azure server through angular 2 using ngx-uploader. For upoloading to azure blob storage we i have to make upload url to be dynamically changed with uploading filename. i have tried to make url dynamic in startupload function as below, But it didnt helped me.

>
`** startUpload(file: UploadFile): void {  // manually start uploading
const event: UploadInput = {
  type: 'uploadAll',
  //  url: this.fileUploadUrl,
  //  method: 'POST',
  url :'https://mysampleoxy.blob.core.windows.net/videos/'+file.name+'??sv=2016-05-31&ss=bfqt&srt=sco&sp=rwdlacup&se=2017-06-06T22:05:22Z&st=2017-05-30T02:05:22Z&spr=https&sig=dpuU5tSW4SOCDiol%2BScLbVw0YtVjmVW6M7Ij8TPGRD4%3D',
  method: 'PUT',
  data: { foo: 'bar' },
  concurrency: 1 // set sequential uploading of files with concurrency 1
}

this.uploadInput.emit(event);

iam not getting where to made the url dynamic

any suggestions will help me alot

**Comment by jkuri** [comment]
this should work, do you get any console errors?

**Comment by chinna-magapu** [comment]
Thanks @jkuri  for your response.

Yes it was working in case of uploading the single file, 
But when i'm trying to upload multiple files it is using the same url  i .e, 

url :'https://mysampleoxy.blob.core.windows.net/videos/'+file.name+'??sv=2016-05-31&ss=bfqt&srt=sco&sp=rwdlacup&se=2017-06-06T22:05:22Z&st=2017-05-30T02:05:22Z&spr=https&sig=dpuU5tSW4SOCDiol%2BScLbVw0YtVjmVW6M7Ij8TPGRD4%3D',

is used by the uploader for uploading the all remaining files,

so i am getting overwrited by the all other files with the first/last file name  in the queue ,
I am not getting the where actuall XHR request is firing to update the url for every file name 
could you help me on this to resolve the issue

**Comment by LintonBlack** [comment]
Hi @chinna-magapu, did you find any solution to your problem to make the url dynamic ?
