### ISSUE TITLE
uploadInput not found issue

### ISSUE THREAD

**Issue by sai2197** [bleenco/ngx-uploader#284]
Template parse errors:
Can't bind to 'uploadInput' since it isn't a known property of 'input'.

It comes out as a rejected promise at the beginning of my angular2 application.

**Comment by aochoa017** [comment]
Hi sai2197,
Don't forget to update **app.module.ts**:

`
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { NgUploaderModule } from 'ngx-uploader';

@NgModule({
  imports: [
    BrowserModule,
    NgUploaderModule
  ],
  declarations: [ AppComponent ],
  exports: [ AppComponent ]
})
export class AppModule {}
`
