### ISSUE TITLE
Questions regarding Observables in codebase 

### ISSUE THREAD

**Issue by adam-beck** [bleenco/ngx-uploader#289]
I'm not for sure where the best place to ask questions is so I opened an issue in case anybody else was interested in the technicalities of the codebase. I have two questions:

1) Why in the `NgUploaderService` is `combineLatest` being used for the `'uploadAll` event?

```js
const subscription = Observable.from(this.files.map(file => this.uploadFile(file, event)))
  .mergeAll(concurrency)
  .combineLatest(data => data)
  .subscribe(subscriber);
```
Wouldn't the `mergeAll` only return 1 stream and also flatten the array of observables?

2) Why use `Subscriber.create(...)` instead of just creating a function expression?

```js
const subscriber = Subscriber.create((data: UploadOutput) => {
  this.serviceEvents.emit(data);
});
```

**Comment by jkuri** [comment]
Hi Adam, 
for the `2.` I found this way more readable but for `1.` if you see that this thing can be improved and work better that way please feel free to open a PR and I will accept it.

**Comment by adam-beck** [comment]
Unfortunaley I don't have enough experience with Observables/rxjs to fully understand what's going on here and if it could be improved or not. I was hoping you would be able to explain why you chose to do it this way so I could better understand. I wasn't criticizing your work; I was just trying learn from it.

**Comment by retailify** [comment]
@adam-beck maybe this help you out [rx-book](https://xgrommx.github.io/rx-book/). ;)
