### ISSUE TITLE
Cannot resolve all parameters for 'NgFileSelect'

### ISSUE THREAD

**Issue by balajijana** [bleenco/ngx-uploader#34]
Hi,

 I am facing an issue when using ng2-uploader: 
EXCEPTION: Error: Uncaught (in promise): Cannot resolve all parameters for 'NgFileSelect'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'NgFileSelect' is decorated with Injectable.

Please let me know how to resolve this issue.

**Comment by antitoine** [comment]
Hi,

After switching from SystemJS to Webpack, I have the same issue, anyone have a solution to fix that?

**Comment by antitoine** [comment]
Duplicate issue, see : https://github.com/jkuri/ng2-uploader/issues/16
