### ISSUE TITLE
How can I append data to each uploaded file?

### ISSUE THREAD

**Issue by OnlyBelter** [bleenco/ngx-uploader#343]
Hi, this component for uploading files is the best one I have ever found! Thank you for your great work. 

Now I need to upload several different files(same file types, different content) through different input box, so I need to distinguish them. How can I add some tags to each file when it emit to uploader?

I am reading the [demo code](https://github.com/jkuri/ngx-uploader/blob/master/src/components/app-home/app-home.component.ts), but don't understand when the function `startUpload` was called.

**Comment by OnlyBelter** [comment]
Actually, I think this is still a problem. Since we can only append data with an event of `UploadInput`, if we have multiple files and some of them have the same file name, then we cannot distinguish them in the back end. 
We need a way to append data (some particular information about this file, like a unique id) for each single file, instead of setting only one `data` for multiple files.

**Comment by OnlyBelter** [comment]
#354 This issue may have same requirement.

**Comment by retailify** [comment]
We are creating following directory structure on the server side:
``` bash
 /<customer assetkey>/<related model>/<directory hash>/file.name
```
The directory hash is currently the unix timestamp, so we have not to deal with "same name" problem. Furthermore we are creating related directories for thumbs. 
If we need to delete the image, we are removing the directory and the database row (in a transaction).

**Comment by OnlyBelter** [comment]
If I understand your point correctly, you mean we have to save each file into separate folder, right??

I use django on the server side, so I save these files by a custom directory, like `/home/user/abc.txt`. And I need to save all files into one folder.

**Comment by retailify** [comment]
Yes, thats the way, we're doing it. 
On the server side, you can check the filename and then rename the file. 

- First upload of abc.txt -> abc.txt
- Second upload of abc.txt -> abc_1.txt

I think you can do this with django also.
