### ISSUE TITLE
concurrency does not exist in type 'UploadInput'

### ISSUE THREAD

**Issue by celsomtrindade** [bleenco/ngx-uploader#348]
When trying to set `concurrency` on the event, I get this error:

> concurrency does not exist in type 'UploadInput'

When looking on the [source code](https://github.com/jkuri/ngx-uploader/blob/master/src/ngx-uploader/classes/interfaces.ts#L52-L62) I noticed it isn't there, but it does appear on the doc on the readme file.

Does this option still existis?

**Comment by jkuri** [comment]
hi. yes it does exists and it actually works (which before wasn't). 
please check here: https://github.com/jkuri/ngx-uploader/blob/master/src/components/app-home/app-home.component.ts#L20

**Comment by celsomtrindade** [comment]
Humm.. Weird.. I don't if it's just my environment, but I get compilation errors, and can't proceed, when trying to define this option. I'm using `angular-cli` in my project. 

In my case, it's not a big deal, but i tought it would be nice to point this.

**Comment by jkuri** [comment]
:) did you checked the url I pasted above? its not from the UploadInput event...

**Comment by celsomtrindade** [comment]
Yes, I did. But what I meant to say is that on your readme file, there is the UploadInput interface and it says:

    concurrency?: number; // concurrency of how many files can be uploaded in parallel (default is 0 which means unlimited)

However, as I mentioned on the question link, the interface on the code doesn't have that option. The way you did, like on the link above, it's different.

I don't know if I'm missing something or didn't understood how it's supposed to work. But hopefully I can make myself clear now. =D

**Comment by jkuri** [comment]
sorry, I need to update readme file, yes. did that concurrency thing working last weekend but forgot to update readme :(. thanks for notice

**Comment by retailify** [comment]
checked readme.
