### ISSUE TITLE
Is ngUploaderService deprecated?

### ISSUE THREAD

**Issue by TakahiRoyte** [bleenco/ngx-uploader#350]
Hello,
I've been using ngx-uploader 2.X.X and I just realized that latest versions are available.
In 2.X.X ngUploaderService was available both in code and document, but in 4.0.0, it is still out there in your code but not in document(README.md).  Is this mean the service has become deprecated?  Should I avoid using it for future?
Thanks

**Comment by retailify** [comment]
Hi @TakahiRoyte, could you please check the Readme again?
Thank you!

**Comment by retailify** [comment]
I will update the readme. 2.x.x, 3.x.x are deprecated. We are not maintaining the code.
