### ISSUE TITLE
'Done' event never fires

### ISSUE THREAD

**Issue by bigweb** [bleenco/ngx-uploader#351]
**_ngx-uploader.class.ts_**

As you can see observer will emit done event only if **xhr.readyState === XMLHttpRequest.DONE**, but this expression is never true, so done event never fires. I debugged several times and it doesn't enter in this block. Afterwards, i changed **XMLHttpRequest.DONE to 4** (which is value for DONE) and everything start to work
```

xhr.onreadystatechange = () => {
	if (xhr.readyState === XMLHttpRequest.DONE) {
	  const speedAverage = Math.round(file.size / (new Date().getTime() - progressStartTime) * 1000);
	  file.progress = {
	    status: UploadStatus.Done,
	    data: {
	      percentage: 100,
	      speed: speedAverage,
	      speedHuman: `${humanizeBytes(speedAverage)}/s`,
	      startTime: progressStartTime,
	      endTime: new Date().getTime(),
	      eta: eta,
	      etaHuman: this.secondsToHuman(eta || 0)
	    }
	  };

	  file.responseStatus = xhr.status;

	  try {
	    file.response = JSON.parse(xhr.response);
	  } catch (e) {
	    file.response = xhr.response;
	  }

	  observer.next({ type: 'done', file: file });

	  observer.complete();
	}
};
```

**Comment by leo6104** [comment]
this issue is long time not resolved issue.

https://stackoverflow.com/questions/6898559/problem-with-xmlhttprequest-done-values

**Comment by AlanCrevon** [comment]
Hi.  I had the same problem but upgrading to 4.0.2 fixed it :)

Hope it helps.
