### ISSUE TITLE
【solved】token authorization

### ISSUE THREAD

**Issue by OnlyBelter** [bleenco/ngx-uploader#356]
In case you need to send files with token authorization, and you don't know how to add proper `headers`, this is the right place. It takes me a lot of time, so I write it down:

```
startUpload(): void {
  let token = this.myToken;  // <----  get token
  const event: UploadInput = {
    type: 'uploadAll',
    url: 'http://ngx-uploader.com/upload',
    method: 'POST',
    headers: { 'Authorization': 'JWT ' + token },  // <----  set headers
    data: { foo: 'bar' }
  };

  this.uploadInput.emit(event);
}
```
Don't need to set `withCredentials`, then you can see it in `request.META['HTTP_AUTHORIZATION'] `: 'JWT eyJhbGciOiJIUzI1NiIsInR5c...', and you can get `request.user`.

In source code, `headers` was set at [here](https://github.com/jkuri/ngx-uploader/blob/master/src/ngx-uploader/classes/ngx-uploader.class.ts#L239)

I use Angular 4.x, Django1.10, Django REST framework 3.6.4 and Django Rest framework JWT 1.11

**Comment by retailify** [comment]
Thank you, I've placed it in the README for the next release.

**Comment by retailify** [comment]
#381 updated Readme
