### ISSUE TITLE
4.0.2 : Progress is not updated while uploading

### ISSUE THREAD

**Issue by AlanCrevon** [bleenco/ngx-uploader#364]
Hi.

Using 4.0.2, any event having `type = 'uploading'` has the same `progress` properties as the start event.

Here it's :

```
endTime : 1508934843984
eta : 0
etaHuman : "00:00:00"
percentage : 100
speed : 106515
speedHuman : "104.02 KB/s"
startTime : 1508934841243
```

Because of this, i can't provide the uploading progress bar i would really need.

Tell me if i can give you anything else to help.

**Comment by retailify** [comment]
Please look at [app-home.component.html](https://github.com/bleenco/ngx-uploader/blob/master/src/components/app-home/app-home.component.html) and [app-home.component.ts](https://github.com/bleenco/ngx-uploader/blob/master/src/components/app-home/app-home.component.ts).

**Comment by retailify** [comment]
I'm closing the issue, cause I've got no feedback.

**Comment by iamwhitebox** [comment]
+1 I am not seeing this functioning correctly
