### ISSUE TITLE
how to get the contents of an uploaded file

### ISSUE THREAD

**Issue by jmls** [bleenco/ngx-uploader#365]
This may seem a really, really stupid question .. but how do I get the contents of a file once it has been uploaded ?

I want to drag a json file onto the browser and parse the json contained within

Go easy - it's been a long, long day and my brain is fried ... 

:)

**Comment by jkuri** [comment]
hi @jmls. you need to read file on the server side and send back contents in response.

**Comment by jmls** [comment]
wait ... what ? Why can't the angular client get the data ?

**Comment by jkuri** [comment]
I am not sure. Why do you need upload service if thats possible?

Maybe you can try something like that:
```ts
onUploadOutput(output: UploadOutput): void {
  if (output.type === 'addedToQueue'  && typeof output.file !== 'undefined') {
    const file: File = output.file.nativeFile;
    const reader = new FileReader();
    reader.onload = (e) => console.log(JSON.parse(e.target.result));
    reader.readAsBinaryString(file);
  }
}
```
... but I never tried this. Please let me know if works.

**Comment by jmls** [comment]
I want to load some json into a structure inside angular and manipulate it before sending it to the server

I'll give that a try - thanks very much

**Comment by jmls** [comment]
perfect ! worked first time. Thank you _so_ much !

**Comment by jmls** [comment]
mmm, actually, one more issue : when dragging and dropping the json file over the "drop container", the browser shows the file contents rather than invoking the function ... ie it displays the raw json file.

Any idea why this would be ?

**Comment by jkuri** [comment]
how do you mean raw JSON file? did you include JSON.parse, or remove the JSON.parse if needed?

**Comment by jmls** [comment]
I mean if I drag the file and drop it on the drop container, the browser does this ...

![image](https://user-images.githubusercontent.com/929523/32123476-364b8336-bb5c-11e7-954a-4938862c5552.png)

**Comment by jkuri** [comment]
![drag-n-drop](https://user-images.githubusercontent.com/1796022/32124192-33ab65be-bb67-11e7-80d1-9a932fabb5e8.gif)

I tried this and it works. Looks like you don't have `ngFileDrop` directive applied on the drop container.

```html
<div ngFileDrop [options]="options" (uploadOutput)="onUploadOutput($event)" [uploadInput]="uploadInput"></div>
```

**Comment by jmls** [comment]
I didn't - sometimes it's the obvious thing ... thanks again

**Comment by jkuri** [comment]
you welcome.

**Comment by jmls** [comment]
one last question : may I ask what tool you used to capture the animation above ?

**Comment by jkuri** [comment]
https://getkap.co/
