### ISSUE TITLE
Unexpected value 'NgUploaderModule'  found after update to 4.1.0 from pre latest

### ISSUE THREAD

**Issue by vincent-cm** [bleenco/ngx-uploader#368]
Unexpected value 'NgUploaderModule' imported by the module 'XXXXX'. Please add a @NgModule annotation.

**Comment by Yacoub89** [comment]
tri solved it by doing this:
import { NgUploaderModule } from 'ngx-uploader/src/ngx-uploader/module/ngx-uploader.module';

**Comment by jkuri** [comment]
`4.1.0` is compiled for Angular 5 already. to use module with Angular 2 or 4 use version prior to `4.1.0`.

**Comment by lacroixdavid1** [comment]
It is not working for me with Angular 2 and 4.1.0 @jkuri

**Comment by jkuri** [comment]
or
```ts
import { NgUploaderModule } from 'ngx-uploader/ngx-uploader';
```
should work also.

**Comment by nishant0131** [comment]
Thanks @jkuri @Yacoub89. Also works for me.

**Comment by fpmk** [comment]
I have error also:

```
ERROR in ./node_modules/ngx-uploader/ngx-uploader.ts
Module build failed: Error: C:\myproj\node_modules\ngx-uploader\ngx-uploader.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (C:\myproj\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:629:23)
    at plugin.done.then (C:\myproj\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./src/app/app.module.ts 34:0-61

```

maybe its anglar issue https://github.com/angular/angular-cli/issues/8284

**Comment by kotsias** [comment]
Hi. This is an issue on angular v 5.0 but if you run **ng serve --aot** will work. This is because in angular 5.0 the node_modules need to be compiled and not contains .ts files. Please fix this plugin to use the compiled files for importion only. Thanks a lot. Nice work.

**Comment by jkuri** [comment]
@kotsias I published `4.1.1` version without source files. Please check if it works.

**Comment by vincent-cm** [comment]
@jkuri Cannot find name 'UploadFile'. is a new issue in 4.1.1

**Comment by jkuri** [comment]
4.1.1 is not good. I just published `4.1.2` please check this version, it should work with `ng serve` and with `ng serve --aot` as well.

**Comment by jkuri** [comment]
https://github.com/bleenco/ngx-uploader/commit/6b0c1e1ff9579541c9e457308e2e49b6ce264b7d for reference.

**Comment by lacroixdavid1** [comment]
@jkuri i'll confirm next week !

**Comment by fibinger** [comment]
It works for me now. Thanks!
