### ISSUE TITLE
IE11 throws SyntaxError when xhr.open is called with an empty string as the url

### ISSUE THREAD

**Issue by stevenruizhang** [bleenco/ngx-uploader#376]
when i upload the file , the file name will display in the input box. But after uploading the file successfully i re select the same file name again the input box file name is empty. This only happen in IE11 but works well in chrome. The reason i set the URL to empty is that i don't want to upload file really, i just process the file data. 
![fileuploadissue](https://user-images.githubusercontent.com/13114985/32687257-603225d6-c6f3-11e7-81d3-c3590305a0d1.PNG)

 fileUploaderOptions: NgUploaderOptions = {
    // url: 'http://localhost:4200/assets/csv',
    url: '',
  };

**Comment by retailify** [comment]
What do you mean with: "i just process the file data"?
Do you emit "this.uploadInput.emit(event);" in your onUploadOutput method?

**Comment by retailify** [comment]
I'm closing the issue. Please respond, if you have further questions.
