### ISSUE TITLE
RESPONSE!???

### ISSUE THREAD

**Issue by kerimdragolj** [bleenco/ngx-uploader#396]
How do i get response, i need to return file name cause i'm generating name on backend, so how do i return it in response???

**Comment by jkuri** [comment]
please check the readme.

**Comment by kerimdragolj** [comment]
i did, like 10x just today, still dont get it.. i mean im passing it in response, but how do i track uploading progress? im sending it in response so when percentage is 100%, but how to track it?

**Comment by jkuri** [comment]
this question is not related to module itself but you need a understanding of how to handle events with the web applications. closing.

**Comment by kerimdragolj** [comment]
ty for help

**Comment by jkuri** [comment]
clone the repo you have everything setted up.
