### ISSUE TITLE
Unable to get DONE status when using with pace.js

### ISSUE THREAD

**Issue by vivian7169** [bleenco/ngx-uploader#398]
[pull request] 
My app is using pace.js(v1.0.2) and ngx-uploader(v4.2.1), and upgraded angular to 5.x. 
After upgrade, uploader is unable to capture DONE status when completed upload.

So I modified the code in lib/src/ngx-uploader/classes/ngx-uploader.class.js
if (xhr.readyState === XMLHttpRequest.DONE)
to 
if (xhr.readyState === 4)

Then it can work. If possible to pull this request into ngx-uploader? 

Thanks.

**Comment by retailify** [comment]
Hi @vivian7169,  is declared in [XMLHttpRequest.DONE](https://github.com/Microsoft/TypeScript/blob/477c1f57a985f3336475e9e65d323e5455df3e75/lib/lib.es6.d.ts#L19584) lib.es6.d.ts from Microsoft. So we don't accept this pull request. 

Please fork ngx-uploader  repo and check your dependencies.
