### ISSUE TITLE
[mime-types] only upload excel & word files

### ISSUE THREAD

**Issue by HEHEMonster** [bleenco/ngx-uploader#399]
![image](https://user-images.githubusercontent.com/16699173/33710247-ec9517d6-db7a-11e7-9a76-696cde333628.png)
How can i init this 'allowedContentTypes'  arr to restrict  only upload excel file ?

**Comment by retailify** [comment]
It depends, cause excel has more than one mime type.
Check this out:

*.xlsx:
`
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
`

*.xls, *.xla:
`
application/msexcel
`

*.docx:
`
application/vnd.openxmlformats-officedocument.wordprocessingml.document
`

This is a [german](https://wiki.selfhtml.org/wiki/MIME-Type/%C3%9Cbersicht) list of known mime types

**Comment by retailify** [comment]
This is [german list of known mime types](https://wiki.selfhtml.org/wiki/MIME-Type/%C3%9Cbersicht). You'll find the needed mime types. If you copy them, remove the white spaces ;)

**Comment by HEHEMonster** [comment]
Thank you,it's work for me,the german list is nice
