### ISSUE TITLE
Can't configure UploaderOptions

### ISSUE THREAD

**Issue by lijinlar** [bleenco/ngx-uploader#401]
There is no documentation for configuring UploaderOptions.
I have configured with following format and it stopped working. No files were added to the files array.
 

`{ allowedContentTypes:["image"] }`

Using with Angular 5.0.2

**Comment by retailify** [comment]
He @lijinlar thats not true, please look at the readme, section Uploader restrictions! There is also a link to a working example or fork the repo an run it....

**Comment by lijinlar** [comment]
@retailify  Ok , will try that.

**Comment by retailify** [comment]
Did you find the solution?

**Comment by lijinlar** [comment]
@retailify  Yes, I was bit confused with documentation tried with sample code and it worked.
Thank you.
