### ISSUE TITLE
aot build error with angular 5.1.2, ngx-uploader 4.2.1

### ISSUE THREAD

**Issue by vincent-cm** [bleenco/ngx-uploader#405]
client:157 ./node_modules/ngx-uploader/src/ngx-uploader/directives/ng-file-drop.directive.ts
Module build failed: Error: ./node_modules/ngx-uploader/src/ngx-uploader/directives/ng-file-drop.directive.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (./node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:649:23)
    at plugin.done.then (./node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
 @ ./src/app/modules/setting/profile-settings/avatar/avatar.ngfactory.js 17:9-83
 @ ./src/app/modules/setting/profile-settings/profile-settings.ngfactory.js
 @ ./src/app/modules/setting/setting.ngfactory.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/main.browser.ts
msgErrors @ client:157
onmessage @ socket.js:38
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
wrapFn @ zone.js:1166
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
ZoneTask.invokeTask @ zone.js:499
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
client:157 ./node_modules/ngx-uploader/src/ngx-uploader/directives/ng-file-select.directive.ts
Module build failed: Error: ./node_modules/ngx-uploader/src/ngx-uploader/directives/ng-file-select.directive.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (./node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:649:23)
    at plugin.done.then (./node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
 @ ./src/app/modules/setting/profile-settings/avatar/avatar.ngfactory.js 18:9-85
 @ ./src/app/modules/setting/profile-settings/profile-settings.ngfactory.js
 @ ./src/app/modules/setting/setting.ngfactory.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/main.browser.ts
msgErrors @ client:157
onmessage @ socket.js:38
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:883
SockJS._transportMessage @ sockjs.js:881
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2957
wrapFn @ zone.js:1166
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
ZoneTask.invokeTask @ zone.js:499
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
client:157 ./node_modules/ngx-uploader/src/ngx-uploader/module/ngx-uploader.module.ts
Module build failed: Error: ./node_modules/ngx-uploader/src/ngx-uploader/module/ngx-uploader.module.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (./node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:649:23)
    at plugin.done.then (./node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
 @ ./src/app/app.module.ngfactory.js 112:11-78
 @ ./src/main.browser.ts
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/main.browser.ts

**Comment by doronsever** [comment]
Happens to us as well. When moving back to 5.1.1 it works as expected

**Comment by doronsever** [comment]
I was manage to get this to work after adding this to the `tsconfig.app.json` file

`
"include": [
    "./**/*.ts",
    "../node_modules/ngx-uploader/src/ngx-uploader/**/*.ts"
  ],
`

I also add this to the `exclude` section but i'm not sure it is needed
`
"exclude": [
    "test.ts",
    "**/*.spec.ts",
    "../node_modules/ngx-uploader/src/**/*.spec.ts"
  ]`
`

**Comment by dima11221122** [comment]
ngx-uploader has wrong build process. At least, published package doesn't have contains ALL sources. Only .d.ts files.

**Comment by abnersouza** [comment]
Having the same issue after upgrading from Angular from 5.1.0 to 5.2.0
