### ISSUE TITLE
How filter's list allows initialization to select one item？

### ISSUE THREAD

**Issue by lliiuu** [bleenco/ngx-uploader#407]
Who knows? Thank you

**Comment by retailify** [comment]
[look here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file)

**Comment by lliiuu** [comment]
please help me?thanks

**Comment by retailify** [comment]
I can not read your mind ;) Please be more specific and describe what you want.

**Comment by lliiuu** [comment]
thanks，my problem，Is another component of the problem，Thank you very much
