### ISSUE TITLE
type not assignable to UploadInput

### ISSUE THREAD

**Issue by zorino** [bleenco/ngx-uploader#411]
Type '{ type: "uploadAll"; url: string; method: string; data: {}; headers: { A
uthorization: string; }; ...' is not assignable to type 'UploadInput'.                                                                                                                                                                     
  Object literal may only specify known properties, and 'concurrency' does not exist in type 'UploadInput'.

With
"ngx-uploader": "^4.2.1"
and angular ^4.0.1

**Comment by jkuri** [comment]
check documentation.

**Comment by zorino** [comment]
ok but it seems in the readme that the property concurrency is still part of the UploadInput interface no ?

**Comment by jkuri** [comment]
its not anymore

**Comment by zorino** [comment]
alright thanks
