### ISSUE TITLE
How to handle maxsize of file ? 

### ISSUE THREAD

**Issue by vaibhavmehtaa** [bleenco/ngx-uploader#435]
can' we provide the maxSize of the file in option, currently, there are only two(allowedContentTypes, concurrency)?
If I check manually the file size but I can't abort the process of uploading file, I've tried with cancel event and other options too but didn't work out, File will upload in any way.
Let me know the if I can validate the size of the file before upload getting started.

**Comment by vovikdrg** [comment]
YOu can do it on onUploadOutput event you have native file in there
