### ISSUE TITLE
File names are encoded

### ISSUE THREAD

**Issue by altso** [bleenco/ngx-uploader#464]
As of `6.0.3`, when I upload a file with spaces in the name (e.g. `my file.txt`), it's transmitted to a server as `my%20file.txt`. Is it an expected behavior or a side effect of f16295a1b7d273b30e01dc6fe1b95f25c220e419?

In this specific case, I'd expect the original unencoded file name.

**Comment by altso** [comment]
@jkuri done. See #465

**Comment by jkuri** [comment]
thanks, merged.
