### ISSUE TITLE
Extend peer dependencies to Angular 7

### ISSUE THREAD

**Issue by agil-NUBBA** [bleenco/ngx-uploader#472]
**Issue description**

running `npm install` throws the following warning:

```
npm WARN ngx-uploader@6.1.0 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-uploader@6.1.0 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
```
**Steps to reproduce and a minimal demo of the problem**

`npm install` with Angular 7

**Current behavior**

`npm install` shows a couple of warning due to peer dependencies.

**Expected/desired behavior**

No warnings should be shown

**Comment by samfrach** [comment]
please upgrade :)

**Comment by jkuri** [comment]
https://github.com/bleenco/ngx-uploader/commit/b423316cebc0f0a1089595e2ef825cba832e057e
