### ISSUE TITLE
TLS problem for https://ngx-uploader.com/

### ISSUE THREAD

**Issue by kolkov** [bleenco/ngx-uploader#493]
https://www.ssllabs.com/ssltest/analyze.html?d=ngx-uploader.com&latest 
for
https://ngx-uploader.com/ 
![image](https://user-images.githubusercontent.com/3740898/58712520-65bc1180-83c9-11e9-9d13-f8ad34225649.png)

**Comment by irmana** [comment]
Fixed https://github.com/bleenco/ngx-uploader/issues/519
