### ISSUE TITLE
ngx-uploader.com

### ISSUE THREAD

**Issue by jkuri** [bleenco/ngx-uploader#519]
Can someone from @bleenco renew certificate for https://ngx-uploader.com please. Otherwise this looks kinda abandoned.

/cc @irmana

**Comment by DavideViolante** [comment]
Duplicate of https://github.com/bleenco/ngx-uploader/issues/493

**Comment by irmana** [comment]
I apologize for the delay and thanks for reporting. This should be fixed now. /cc @belsakn 

-- Irman
