### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by karandesai28** [bleenco/ngx-uploader#68]
Two questions: 
1. What is the use of [ng-file-select]? Can I pass its object value null?
2. In this code, the code breaks at "this.uploadFile" and console says the error: Unexpected token < in JSON at position 0.

```
uploadFile: any;
if (data && data.response) {
            data = JSON.parse(data.response);
            this.uploadFile = data;
        }
```

Any assistance appreciated. Thanks.

**Comment by sbahmani** [comment]
`data.response` is the  response that reset file handler serve it.
