### ISSUE TITLE
implement with pure javascript

### ISSUE THREAD

**Issue by BehnamAbdy** [bleenco/ngx-uploader#72]
i want to know how can i import and use ng2-uploader in my angular2 app written in pure javascript (not typescript).
i've already added the reference to ng2-uploader.js and when i add the UPLOAD_DIRECTIVES  to my app.componen.js attributes things crash

(function (app) {
    app.AppComponent =
      ng.core.Component({
          selector: 'app',
          templateUrl: 'app/components/app.component.html',
          styleUrls: ['app/components/app.component.css'],
          directives: [ng.router.ROUTER_DIRECTIVES, ng2-uploader.UPLOAD_DIRECTIVES]
      })
      .Class({
          constructor: [ng.router.Router, function (router) {
              this.router = router;  
          }],
          go: function () {  
              this.router.navigate(['/clients']);
          }
      });
})(window.app || (window.app = {}));

**Comment by jkuri** [comment]
Honestly I never tried using universal, what is the console error output?

**Comment by BehnamAbdy** [comment]
here are errors:

Uncaught ReferenceError: require is not defined     
Uncaught ReferenceError: ng2 is not defined
Uncaught Unexpected value 'undefined' declared by the module 'constructor'

**Comment by jkuri** [comment]
I am guessing that importing as `ng2-uploader.UPLOAD_DIRECTIVES` is not correct.
