### ISSUE TITLE
How to preview image?

### ISSUE THREAD

**Issue by shuidian** [bleenco/ngx-uploader#74]
is there any way to get the img preview data?

**Comment by jkuri** [comment]
Hey @shuidian. Yes, please see http://ng2-uploader.com/advanced and correlated [documentation](http://ng2-uploader.com/docs).

**Comment by choopage** [comment]
I used the img preview too. It is working. Good

**Comment by NGizdov** [comment]
Sorry, but from these links for the file preview I can't see anything. Please give some examples on how to preview the image before upload.

**Comment by NGizdov** [comment]
There is no documentation on that link

**Comment by evansmwendwa** [comment]
Anyone figured how to do the preview? Would be good to have an example using all the available options and events.

**Comment by evansmwendwa** [comment]
For the preview to work you have to set the previewUrl options to some text (not sure why it's not boolean) and then subscribe to onPreviewData event in the directive.

**Comment by celsomtrindade** [comment]
I just made an answer for this on this question #257
