### ISSUE TITLE
Upload mutiple files bug!

### ISSUE THREAD

**Issue by mickeychu** [bleenco/ngx-uploader#77]
Hi, I realized that there's a bug when uploading files. 

Here's the use case: 
I just want the user of my app to upload 1 file at a time. But, if I choose a file, not upload it then choose another one then click upload (I want to upload file manually by a button) So both files will be uploaded to the server. (So if I choose more and more, all files will be uploaded to the server.)

Here's my code: 

```
ts:

 handleUpload(data): void {
    if (data && data.response) {
      data = JSON.parse(data.response);
    }
  }

  startUpload() {
    this.uploadEvents.emit('startUpload');
  }


html:

<input type="file" formControlName="upload" class="upload_input"
             ngFileSelect
             (onUpload)="handleUpload($event)"
             [events]="uploadEvents"
             [options]="options"
             (change)="get_name($event)">
```

I just want to upload the latest file that user choose, not all the files that they have chosen.

**Comment by jkuri** [comment]
Hey,

I know, there's a problem with FileList API which is readonly.

**Comment by mickeychu** [comment]
hmm, so is there any manual way to fix this? Or at least just upload the latest chosen file?

**Comment by mickeychu** [comment]
will this be fixed in the next release @jkuri  ?

**Comment by palpa** [comment]
I'm also facing the same issue, any fix?
