### ISSUE TITLE
I needed to change systemjs.config.js after installing.

### ISSUE THREAD

**Issue by kolkov** [bleenco/ngx-uploader#81]
Hi!
I needed to change systemjs.config.js after installing.
But nothing about it in docs.))

**Comment by pulgaroja** [comment]
Hello @kolkov I tried adding it to my systemjs.config.js but it is still not recognized in my app.module.ts. Here are the changes I made:
`// map tells the System loader where to look for things
  var map = {
    'app':                        'app', // 'dist',

    '@angular':                   'node_modules/@angular',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    'moment':                     'node_modules/moment',
    'rxjs':                       'node_modules/rxjs',
    'ng2-uploader':               'node_modules/ng2-uploader',
  };

  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
    'moment':                     { main: 'moment.js', defaultExtension: 'js' },
    'ng2-uploader':               { main: 'ng2-uploader.js', defaultExtension: 'js' },
  };`

How did you get it to work? What am I missing? 
Thank you so much.

**Comment by rezikovka** [comment]
@pulgaroja , may be you should use in app.module.ts
 import { UPLOAD_DIRECTIVES } from 'ng2-uploader/ng2-uploader';
instead of
import { UPLOAD_DIRECTIVES } from 'ng2-uploader';
because in your systemjs.config.js you put 'ng2-uploader.js' as main file, but in app.module.ts you write path only to the directory with main file

**Comment by joelflint** [comment]
@kolkov Care to outline the changes you had to make? I think that would help a bunch of people. I have made similar changes as @pulgaroja, but getting lots of errors. Would love a quick outline of the changes as they are "supposed" to be made. Thanks in advance!
