### ISSUE TITLE
allowedExtensions not working

### ISSUE THREAD

**Issue by kolkov** [bleenco/ngx-uploader#82]
When I setup allowedExtensions: ['image/png', 'image/jpg'] like in example, I can't upload jpg files.

> Filter Allowed Extensions with Preview Enabled and Manual Upload
> not working too.

**Comment by jkuri** [comment]
Hi @kolkov please see the README.

**Comment by choopage** [comment]
it's working. I tested it.

**Comment by keithmichelson** [comment]
I had to take out image and just use  ['png', 'jpg']. I don't get an error but it doesn't let it upload.

**Comment by kolkov** [comment]
Not working still as in doc.

**Comment by kolkov** [comment]
`allowedExtensions: ['image/jpeg', 'image/png'],` not `allowedExtensions: ['image/jpg', 'image/png'],`
thats worked.

**Comment by Sn3b** [comment]
Just run into this issue, the values for AllowedExtensions seem to be case sensitive... I had to use:
```javascript
      filterExtensions: true,
      allowedExtensions: ['JPG', 'jpg', 'PNG', 'png']
```

**Comment by Justinemmerich** [comment]
Hey guys,

where do I have to place this 

allowedExtensions: ['image/jpeg', 'image/png'], 

im my component file ?
