### ISSUE TITLE
How to preview and crop images before upload

### ISSUE THREAD

**Issue by kolkov** [bleenco/ngx-uploader#83]
Hi!
I want to crop image and upload it as user avatar.
Do we have events beforeUpload?

**Comment by keithmichelson** [comment]
I'm trying to the same thing using adobe aviary editor. I haven't got it to work but maybe using the preview and startUpload() might help. Bottom page of the docs. http://ng2-uploader.com/docs

Currently I'm just going to upload 2 versions a before and after, I've got the image coming back from the Aviary editor after cropping but I'm not sure how to upload without it automatically uploading on image select.

**Comment by kolkov** [comment]
@keithmichelson I think with using `autoUpload: false`...
