### ISSUE TITLE
File not saving

### ISSUE THREAD

**Issue by keithmichelson** [bleenco/ngx-uploader#93]
I'm using the basic example with Express and I never get a file saved to a folder? I don't get an error but I can run tests and see that the functions are being called. I'm getting the original and new name callback.

Is the image suppose to be in an uploads folder in my express app?

**Comment by jkuri** [comment]
I guess I should update example for express then, maybe is a problem with the plugin for saving not properly configured. Did you maybe resolve this? If so, can you post a fix? Thanks.

**Comment by keithmichelson** [comment]
@jkuri Thanks for replying. I wasn't sure the exact problem but here is what I got to work finally after going through the multer docs. Pretty close to what you had but I'm only doing one file.

`var storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, 'public/uploads/')
  },
  filename: (req, file, cb) => {
    let ext = path.extname(file.originalname);
    cb(null, `${Math.random().toString(36).substring(7)}${ext}`);
  }
});
var upload = multer({ storage: storage, limits: { fileSize: 2000000 } });`

`app.post('/upload', middleware.requireAuthentication, upload.any(), function(req, res){
  var originalName = req.files[0].originalname;
  var newName = req.files[0].filename;

  res.json({
    originalName: originalName,
    filename: newName
  });
});`

**Comment by jkuri** [comment]
@keithmichelson thanks, I'll update the readme with that example.
