### ISSUE TITLE
Multiple files upload with preview

### ISSUE THREAD

**Issue by naveedahmed1** [bleenco/ngx-uploader#95]
Hi,

When uploading multiple files (with preview enabled), it is possible to show the preview image for each of the selected file. But on completion of the image upload, I want to replace the preview of the image with the corresponding uploaded image url.

Since onPreviewData, just provide the Base64 encoded image data without any id of the image, therefore it doesn't seem to be possible to replace the preview image with corresponding uploaded image url.

**Comment by jkuri** [comment]
did you try to replace it with setting `[src]` with response you get?

**Comment by naveedahmed1** [comment]
Yes, this works in case of single file. But in case of multiple files it doesn't work because it doesn't know which preview to replace.

**Comment by simkepal** [comment]
+1

**Comment by Alessandro77** [comment]
try this way for now:
create a empty public array that can collect originalName reference of each file from the event beforeUpload.
onPreviewData can read this array and associate the first occurrence whit the previewdata url, then shift the array.
It works ;)

--------

tempname=[];
beforeUpload(uploadingFile: UploadedFile): void {
    this.tempname.push(uploadingFile.originalName);
}

handlePreviewData(data: any) {
    this.previewData.push({"src":data,"originalName":this.tempname[0]});
    this.tempname.shift();
  }
