### ISSUE TITLE
maxUploads Limit dooest seem to work

### ISSUE THREAD

**Issue by naveedahmed1** [bleenco/ngx-uploader#96]
Hi,

It seems that the maxUploads options doesn't seem to work. 

I assume that maxUploads options should allow us to set a limit on maximum concurrent uploads.

**Comment by jkuri** [comment]
yes, if I remember correctly this is not implemented yet.

**Comment by naveedahmed1** [comment]
Any plans to implement it soon? Can you please guide how to enforce it in the service?

**Comment by jkuri** [comment]
I believe you are looking for this https://developer.mozilla.org/en/docs/Web/API/FileList
