### ISSUE TITLE
Progress is not working

### ISSUE THREAD

**Issue by rashtay** [bleenco/ngx-uploader#98]
I see 1% and then there is no indication of file being uploaded. After few sec the file gets uploaded. Even the progress indicator is not working in the demos.

**Comment by jkuri** [comment]
Yes, there are some issues with upload server.

**Comment by darkkean** [comment]
Also having this issue when I was still in RC4. I thought it will be resolved by upgrading to Angular 2 Final 2.0.1, but still having the error.

I added a console.log on first line of handleUpload function and found out that `data.progress.percent` is immediately set to **100**. On second check, it stays at 100, even the image was already uploaded.

**Comment by F3L1X79** [comment]
I was wondering if the progress indicator can work with a PHP upload file?

**Comment by F3L1X79** [comment]
Finally I can confirm this is working with a PHP upload, but the example in doc was wrong!

I had to change this code:
```
handleUpload(data: any): void {
    this.zone.run(() => {
      this.response = data;
      this.progress = Math.floor(data.progress.percent / 100);
    });
  }
```

by simply this:
```
handleUpload(data: any): void {
        this.zone.run(() => {
            this.response = data;
            this.progress = data.progress.percent; //no need to divide by 100 anymore!
        });
        if (data && data.response) {
            data = JSON.parse(data.response);
        }
    }
```

Hope this helps.
