### ISSUE TITLE
How to implement file-upload and drag and drop together?

### ISSUE THREAD

**Issue by rashtay** [bleenco/ngx-uploader#99]
I am unable to use both the directives in a same block. I wanna give user the option to click and upload or drag and drop.

**Comment by stevedenman** [comment]
Hi @shettyrahul8june, I needed the same - ended up creating 2 uploaders next to each other (one ngFileDrop and one ngFileSelect).

**Comment by shettyrahul8june** [comment]
@stevedenman Yea, even I ended up doing something like that.

Below is the code if someone wants to implement both the features:

```
  <div
    class="front"
    ngFileDrop
    [options]="options"
    (onUpload)="handleUpload($event)"
    multiple="true"
  >
      <div class="drop-box">
        <p class="drag-drop-upload-para">
          Drag & drop files here or
        </p>
      </div>
  </div>

  <form class="front form-upload">
    <input
      type="file"
      ngFileSelect
      [options]="options"
      (onUpload)="handleUpload($event)"
      id="upload-file"
      multiple="true"
    />
    <label for="upload-file">
      <a>Upload</a>
    </label>
  </form>
```

Then, I absolutely positioned the upload link/button next to the drag and drop text. I hope it's correct.
